// src/dialogs/LoginDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useMessage } from 'naive-ui'
import { useStore } from '../store.ts'
import { commands } from '../bindings.ts'
import FloatLabelInput from '../components/FloatLabelInput.vue'

const store = useStore()

const message = useMessage()

const showing = defineModel<boolean>('showing', { required: true })

const username = ref<string>('')
const password = ref<string>('')

async function login() {
  if (store.config === undefined) {
    return
  }
  if (username.value === '') {
    message.error('请输入用户名')
    return
  }
  if (password.value === '') {
    message.error('请输入密码')
    return
  }
  const result = await commands.login(username.value, password.value)
  if (result.status === 'error') {
    console.error(result.error)
    return
  }
  message.success('登录成功')
  store.config.cookie = result.data
  showing.value = false
}
</script>

<template>
  <n-modal v-model:show="showing">
    <n-dialog
      class="flex flex-col"
      :showIcon="false"
      title="账号登录"
      positive-text="登录"
      @positive-click="login"
      @close="showing = false"
      @keydown.enter="login">
      <div class="flex flex-col gap-2">
        <FloatLabelInput label="用户名" v-model:value="username" />
        <FloatLabelInput label="密码" v-model:value="password" type="password" />
      </div>
    </n-dialog>
  </n-modal>
</template>

// src/dialogs/LoginDialog.tsx
import { App as AntdApp, Modal } from 'antd'
import { commands, Config } from '../bindings.ts'
import { KeyboardEvent, useState } from 'react'
import { FloatLabelInput } from '../components/FloatLabelInput.tsx'

interface Props {
  loginDialogShowing: boolean
  setLoginDialogShowing: (showing: boolean) => void
  config: Config
  setConfig: (value: Config | undefined | ((prev: Config | undefined) => Config | undefined)) => void
}

function LoginDialog({ loginDialogShowing, setLoginDialogShowing, config, setConfig }: Props) {
  const { message } = AntdApp.useApp()

  const [username, setUsername] = useState<string>('')
  const [password, setPassword] = useState<string>('')

  async function login() {
    if (username === '') {
      message.error('请输入用户名')
      return
    }

    if (password === '') {
      message.error('请输入密码')
      return
    }

    const key = 'login'
    message.loading({ content: '登录中...', key, duration: 0 })
    const result = await commands.login(username, password)
    message.destroy(key)
    if (result.status === 'error') {
      console.error(result.error)
      return
    }

    message.success('登录成功')
    setConfig({ ...config, cookie: result.data })
    setLoginDialogShowing(false)
  }

  async function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      await login()
    }
  }

  return (
    <Modal
      title="账号登录"
      open={loginDialogShowing}
      onOk={login}
      onCancel={() => setLoginDialogShowing(false)}
      cancelButtonProps={{ style: { display: 'none' } }}
      okText="登录">
      <div className="flex flex-col gap-2" onKeyDown={handleKeyDown}>
        <FloatLabelInput label="用户名" value={username} onChange={(e) => setUsername(e.target.value)} />
        <FloatLabelInput type="password" label="密码" value={password} onChange={(e) => setPassword(e.target.value)} />
      </div>
    </Modal>
  )
}

export default LoginDialog
