// src/panes/ChapterPane.tsx
import { App as AntdApp, Button, Checkbox, CheckboxProps, Dropdown, Empty, MenuProps, Tabs, TabsProps } from 'antd'
import { ChapterInfo, Comic, commands } from '../bindings.ts'
import { useEffect, useMemo, useState } from 'react'
import SelectionArea, { SelectionEvent } from '@viselect/react'
import styles from '../styles/ChapterPane.module.css'

interface Props {
  pickedComic: Comic | undefined
  setPickedComic: (update: (prevComic: Comic | undefined) => Comic | undefined) => void
}

function ChapterPane({ pickedComic, setPickedComic }: Props) {
  const { message } = AntdApp.useApp()
  // 按章节数排序的分组
  const sortedGroups = useMemo<[string, ChapterInfo[]][] | undefined>(() => {
    const groups = pickedComic?.groups
    if (groups === undefined) {
      return
    }
    return Object.entries(groups).sort((a, b) => {
      return b[1].length - a[1].length
    })
  }, [pickedComic?.groups])
  // 第一个group的名字
  const firstGroupName = sortedGroups?.[0]?.[0] ?? '单话'
  // 当前tab的分组名
  const [currentGroupName, setCurrentGroupName] = useState<string>(firstGroupName)

  // 所有章节
  const chapterInfos = useMemo<ChapterInfo[] | undefined>(() => {
    const groups = pickedComic?.groups
    if (groups === undefined) {
      return
    }

    return Object.values(groups).flat()
  }, [pickedComic?.groups])

  // 已勾选的章节id
  const [checkedIds, setCheckedIds] = useState<Set<number>>(new Set())
  // 已选中(被框选选到)的章节id
  const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set())
  // 如果漫画变了，清空勾选和选中状态
  useEffect(() => {
    setCheckedIds(new Set())
    setSelectedIds(new Set())
    // FIXME: 需要调用 SelectionArea实例的 clearSelection() 方法
    setCurrentGroupName(firstGroupName)
  }, [firstGroupName, pickedComic])

  // 下载勾选的章节
  async function downloadChapters() {
    if (pickedComic === undefined) {
      message.error('请先选择漫画')
      return
    }
    // 创建下载任务前，先创建元数据
    const saveMetadataResult = await commands.saveMetadata(pickedComic)
    if (saveMetadataResult.status === 'error') {
      console.error(saveMetadataResult.error)
      return
    }
    // 下载没有下载过的且已勾选的章节
    const chapterToDownload = chapterInfos?.filter((c) => c.isDownloaded === false && checkedIds.has(c.chapterId))
    if (chapterToDownload === undefined) {
      return
    }
    await commands.downloadChapters(chapterToDownload)
    // 把已下载的章节从已勾选的章节id中移除
    setCheckedIds((prev) => new Set([...prev].filter((id) => !chapterToDownload.map((c) => c.chapterId).includes(id))))
    // 更新pickedComic，将已下载的章节标记为已下载
    setPickedComic((prev) => {
      if (prev === undefined) {
        return prev
      }
      const next = { ...prev }
      for (const downloadedChapter of chapterToDownload) {
        const chapter = Object.values(next.groups)
          .flat()
          .find((c) => c.chapterId === downloadedChapter.chapterId)
        if (chapter !== undefined) {
          chapter.isDownloaded = true
        }
      }
      return next
    })
  }

  // 重新加载选中的漫画
  async function reloadPickedComic() {
    if (pickedComic === undefined) {
      return
    }

    const result = await commands.getComic(pickedComic.id)
    if (result.status === 'error') {
      console.error(result.error)
      return
    }

    setPickedComic(() => result.data)
  }

  return (
    <div className="h-full flex flex-col box-border">
      {pickedComic === undefined && <Empty description="请先选择漫画(漫画搜索、漫画收藏、本地库存)" />}
      {pickedComic !== undefined && (
        <>
          <div className="flex items-center select-none pt-2 gap-1 px-2">
            <div>左键拖动进行框选，右键打开菜单</div>
            <Button className="w-13 ml-auto" onClick={reloadPickedComic}>
              刷新
            </Button>
            <Button className="w-27" type="primary" onClick={downloadChapters}>
              下载勾选章节
            </Button>
          </div>

          <ChapterTabs
            pickedComic={pickedComic}
            sortedGroups={sortedGroups}
            setCheckedIds={setCheckedIds}
            selectedIds={selectedIds}
            setSelectedIds={setSelectedIds}
            checkedIds={checkedIds}
            currentGroupName={currentGroupName}
            setCurrentGroupName={setCurrentGroupName}
          />

          <div className="flex p-2 pt-0">
            <img className="w-24 mr-4 object-cover" src={pickedComic.cover} alt="" />
            <div className="flex flex-col h-full">
              <span className="font-bold text-xl line-clamp-3">
                {pickedComic.title}
                {pickedComic.subtitle && `(${pickedComic.subtitle})`}
              </span>
              <span className="text-red">作者：{pickedComic.authors.join(', ')}</span>
              <span className="text-gray">类型：{pickedComic.genres.join(' ')}</span>
            </div>
          </div>
        </>
      )}
    </div>
  )
}

interface ChapterTabsProps {
  pickedComic: Comic
  sortedGroups?: [string, ChapterInfo[]][]
  setCheckedIds: (value: ((prevState: Set<number>) => Set<number>) | Set<number>) => void
  selectedIds: Set<number>
  setSelectedIds: (value: ((prevState: Set<number>) => Set<number>) | Set<number>) => void
  checkedIds: Set<number>
  currentGroupName: string
  setCurrentGroupName: (value: string) => void
}

function ChapterTabs({
  pickedComic,
  sortedGroups,
  setCheckedIds,
  selectedIds,
  setSelectedIds,
  checkedIds,
  currentGroupName,
  setCurrentGroupName,
}: ChapterTabsProps) {
  // 当前分组
  const currentGroup = pickedComic.groups[currentGroupName]

  const items = useMemo<TabsProps['items']>(() => {
    // 提取章节id
    function extractIds(elements: Element[]): number[] {
      return elements
        .map((element) => element.getAttribute('data-key'))
        .filter(Boolean)
        .map(Number)
        .filter((id) => {
          const chapterInfo = currentGroup?.find((chapter) => chapter.chapterId === id)
          return chapterInfo && chapterInfo.isDownloaded === false
        })
    }

    // 取消所有已选中(被框选选到)的章节
    function unselectAll({ event, selection }: SelectionEvent) {
      if (!event?.ctrlKey && !event?.metaKey) {
        selection.clearSelection()
        setSelectedIds(new Set())
      }
    }

    // 更新已选中(被框选选到)的章节id
    function updateSelectedIds({
      store: {
        changed: { added, removed },
      },
    }: SelectionEvent) {
      setSelectedIds((prev) => {
        const next = new Set(prev)
        extractIds(added).forEach((id) => next.add(id))
        extractIds(removed).forEach((id) => next.delete(id))
        return next
      })
    }

    if (sortedGroups === undefined) {
      return []
    }

    const onCheckboxChange: CheckboxProps['onChange'] = (e) => {
      setCheckedIds((prev) => {
        const next = new Set(prev)
        const id = e.target.value
        if (e.target.checked) {
          next.add(id)
        } else {
          next.delete(id)
        }
        return next
      })
    }

    const dropdownOptions: MenuProps['items'] = [
      {
        label: '勾选',
        key: 'check',
        onClick: () =>
          // 将框选选到的章节id加入已勾选的章节id中
          setCheckedIds((prev) => {
            const next = new Set(prev)
            selectedIds.forEach((id) => next.add(id))
            return next
          }),
      },
      {
        label: '取消勾选',
        key: 'uncheck',
        onClick: () =>
          // 将框选选到的章节id从已勾选的章节id中移除
          setCheckedIds((prev) => new Set([...prev].filter((id) => !selectedIds.has(id)))),
      },
      {
        label: '全选',
        key: 'check all',
        onClick: () =>
          // 将当前分组中未下载的章节id加入已勾选的章节id中
          setCheckedIds((prev) => {
            const next = new Set(prev)
            currentGroup?.filter((c) => c.isDownloaded === false).forEach((c) => next.add(c.chapterId))
            return next
          }),
      },
      {
        label: '取消全选',
        key: 'uncheck all',
        onClick: () =>
          // 将当前分组中未下载的章节id从已勾选的章节id中移除
          setCheckedIds(
            (prev) => new Set([...prev].filter((id) => !currentGroup?.map((c) => c.chapterId).includes(id))),
          ),
      },
    ]

    return sortedGroups.map(([groupName, chapters]) => ({
      key: groupName,
      label: groupName,
      children: (
        <Dropdown menu={{ items: dropdownOptions }} trigger={['contextMenu']}>
          <div className="h-full flex flex-col gap-row-1 overflow-auto">
            <SelectionArea
              className={`${styles.selectionContainer} flex flex-col flex-1 box-border pt-2 px-2 overflow-auto h-full`}
              selectables=".selectable"
              features={{ deselectOnBlur: true }}
              onMove={updateSelectedIds}
              onStart={unselectAll}>
              <div className="grid grid-cols-3 gap-1.5 w-full mb-3">
                {chapters.map((chapter) => (
                  <div
                    className={`${selectedIds.has(chapter.chapterId) ? 'selected' : ''} ${chapter.isDownloaded ? 'downloaded' : ''} selectable`}
                    key={chapter.chapterId}
                    data-key={chapter.chapterId}>
                    <Checkbox
                      value={chapter.chapterId}
                      className={styles.antdCheckBox}
                      checked={checkedIds.has(chapter.chapterId)}
                      disabled={chapter.isDownloaded === true}
                      onChange={onCheckboxChange}>
                      <span title={chapter.chapterTitle}>{chapter.chapterTitle}</span>
                    </Checkbox>
                  </div>
                ))}
              </div>
            </SelectionArea>
          </div>
        </Dropdown>
      ),
    }))
  }, [sortedGroups, setSelectedIds, setCheckedIds, selectedIds, currentGroup, checkedIds])

  return (
    <Tabs
      key={pickedComic.id}
      activeKey={currentGroupName}
      className="flex-1 overflow-auto"
      size="small"
      items={items}
      onChange={setCurrentGroupName}
    />
  )
}

export default ChapterPane

// src/panes/ChapterPane.vue
<script setup lang="ts">
import { ChapterInfo, commands } from '../bindings.ts'
import { SelectionArea, SelectionEvent } from '@viselect/vue'
import { computed, nextTick, ref, useTemplateRef, watch, watchEffect } from 'vue'
import { useStore } from '../store.ts'
import { DropdownOption, useMessage } from 'naive-ui'

const store = useStore()

const message = useMessage()

// 按章节数排序的分组
const sortedGroups = computed<[string, ChapterInfo[]][] | undefined>(() => {
  if (store.pickedComic === undefined) {
    return undefined
  }

  return Object.entries(store.pickedComic.groups).sort((a, b) => b[1].length - a[1].length)
})
// 第一个group的名字
const firstGroupName = sortedGroups.value?.[0]?.[0] ?? '单话'
// 当前tab的分组名
const currentGroupName = ref<string>(firstGroupName)
const currentGroup = computed<ChapterInfo[] | undefined>(() => store.pickedComic?.groups[currentGroupName.value])
// SelectionArea组件的ref
const selectionAreaRefs = useTemplateRef('selection-area')

const { dropdownX, dropdownY, dropdownShowing, dropdownOptions, showDropdown } = useDropdown()
const { checkedIds, selectedIds, unselectAll, updateSelectedIds } = useSelectionArea()

const checkedIdsArray = computed<number[]>({
  get: () => [...checkedIds.value],
  set: (next) => (checkedIds.value = new Set(next)),
})

function useDropdown() {
  // dropdown的x坐标
  const dropdownX = ref<number>(0)
  // dropdown的y坐标
  const dropdownY = ref<number>(0)
  // 是否显示dropdown
  const dropdownShowing = ref<boolean>(false)
  // dropdown选项
  const dropdownOptions: DropdownOption[] = [
    {
      label: '勾选',
      key: 'check',
      props: {
        onClick: () => {
          selectedIds.value.forEach((id) => checkedIds.value.add(id))
          dropdownShowing.value = false
        },
      },
    },
    {
      label: '取消勾选',
      key: 'uncheck',
      props: {
        onClick: () => {
          selectedIds.value.forEach((id) => checkedIds.value.delete(id))
          dropdownShowing.value = false
        },
      },
    },
    {
      label: '全选',
      key: 'check all',
      props: {
        onClick: () => {
          currentGroup.value?.filter((c) => c.isDownloaded === false).forEach((c) => checkedIds.value.add(c.chapterId))
          dropdownShowing.value = false
        },
      },
    },
    {
      label: '取消全选',
      key: 'uncheck all',
      props: {
        onClick: () => {
          currentGroup.value?.forEach((c) => checkedIds.value.delete(c.chapterId))

          dropdownShowing.value = false
        },
      },
    },
  ]

  // 显示dropdown
  async function showDropdown(e: MouseEvent) {
    dropdownShowing.value = false
    await nextTick()
    dropdownShowing.value = true
    dropdownX.value = e.clientX
    dropdownY.value = e.clientY
  }

  return { dropdownX, dropdownY, dropdownShowing, dropdownOptions, showDropdown }
}

function useSelectionArea() {
  // 已勾选的章节id
  const checkedIds = ref<Set<number>>(new Set())
  // 已选中(被框选选到)的章节id
  const selectedIds = ref<Set<number>>(new Set())
  // 如果漫画变了，清空勾选和选中状态
  watch(
    () => store.pickedComic,
    () => {
      checkedIds.value.clear()
      selectedIds.value.clear()
      selectionAreaRefs.value?.forEach((ref) => ref?.selection?.clearSelection())
      currentGroupName.value = firstGroupName
    },
  )

  watchEffect(() => {
    if (store.pickedComic === undefined || sortedGroups.value === undefined) {
      return
    }
    // 只保留未下载的章节
    const notDownloadedChapterIds = new Set(
      sortedGroups.value
        .flatMap(([, chapters]) => chapters)
        .filter((c) => c.isDownloaded !== true)
        .map((c) => c.chapterId),
    )

    checkedIds.value = new Set([...checkedIds.value].filter((id) => notDownloadedChapterIds.has(id)))
  })

  // 提取章节id
  function extractIds(elements: Element[]): number[] {
    return elements
      .map((element) => element.getAttribute('data-key'))
      .filter(Boolean)
      .map(Number)
      .filter((id) => {
        const chapterInfo = currentGroup.value?.find((c) => c.chapterId === id)
        return chapterInfo && chapterInfo.isDownloaded === false
      })
  }

  // 取消所有已选中(被框选选到)的章节
  function unselectAll({ event, selection }: SelectionEvent) {
    if (!event?.ctrlKey && !event?.metaKey) {
      selection.clearSelection()
      selectedIds.value.clear()
    }
  }

  // 更新已选中(被框选选到)的章节id
  function updateSelectedIds({
    store: {
      changed: { added, removed },
    },
  }: SelectionEvent) {
    extractIds(added).forEach((id) => selectedIds.value.add(id))
    extractIds(removed).forEach((id) => selectedIds.value.delete(id))
  }
  return { checkedIds, selectedIds, unselectAll, updateSelectedIds }
}

// 下载勾选的章节
async function downloadChapters() {
  if (store.pickedComic === undefined) {
    message.error('请先选择漫画')
    return
  }
  // 创建下载任务前，先创建元数据
  const saveMetadataResult = await commands.saveMetadata(store.pickedComic)
  if (saveMetadataResult.status === 'error') {
    console.error(saveMetadataResult.error)
    return
  }
  // 下载没有下载过的且已勾选的章节
  const chaptersToDownload = currentGroup.value?.filter(
    (c) => c.isDownloaded !== true && checkedIds.value.has(c.chapterId),
  )
  if (chaptersToDownload === undefined) {
    return
  }
  await commands.downloadChapters(chaptersToDownload)
  for (const chapterToDownload of chaptersToDownload) {
    const chapterId = chapterToDownload.chapterId
    // 将已下载的章节标记为已下载
    const chapter = currentGroup.value?.find((c) => c.chapterId === chapterId)
    if (chapter !== undefined) {
      chapter.isDownloaded = true
    }
  }
}

// 重新加载选中的漫画
async function reloadPickedComic() {
  if (store.pickedComic === undefined) {
    return
  }

  const result = await commands.getComic(store.pickedComic.id)
  if (result.status === 'error') {
    console.error(result.error)
    return
  }

  store.pickedComic = result.data
}
</script>

<template>
  <div class="h-full flex flex-col box-border">
    <n-empty v-if="store.pickedComic === undefined" description="请先选择漫画(漫画搜索、漫画收藏、本地库存)" />
    <template v-else>
      <div class="flex items-center select-none pt-2 gap-1 px-2">
        <div>左键拖动进行框选，右键打开菜单</div>
        <n-button class="ml-auto" size="small" @click="reloadPickedComic">刷新</n-button>
        <n-button size="small" type="primary" @click="downloadChapters">下载勾选章节</n-button>
      </div>

      <n-tabs class="flex-1 overflow-auto" v-model:value="currentGroupName" type="line" size="small" animated>
        <n-tab-pane
          v-for="[groupName, chapters] in sortedGroups"
          :key="groupName"
          :name="groupName"
          :tab="groupName"
          class="overflow-auto p-0! h-full">
          <selection-area
            ref="selection-area"
            class="selection-container flex flex-col flex-1 box-border pt-2 px-2 overflow-auto h-full"
            :options="{ selectables: '.selectable', features: { deselectOnBlur: true } }"
            @contextmenu="showDropdown"
            @move="updateSelectedIds"
            @start="unselectAll">
            <n-checkbox-group v-model:value="checkedIdsArray" class="grid grid-cols-3 gap-1.5 w-full mb-3">
              <n-checkbox
                v-for="chapter in chapters"
                :key="chapter.chapterId"
                :data-key="chapter.chapterId"
                class="selectable hover:bg-gray-200!"
                :value="chapter.chapterId"
                :label="chapter.chapterTitle"
                :disabled="chapter.isDownloaded === true"
                :class="{
                  selected: selectedIds.has(chapter.chapterId),
                  downloaded: chapter.isDownloaded,
                }" />
            </n-checkbox-group>
          </selection-area>
        </n-tab-pane>
      </n-tabs>

      <div class="flex p-2 pt-0">
        <img class="w-24 mr-4 object-cover" :src="store.pickedComic.cover" alt="" />
        <div class="flex flex-col h-full">
          <span class="font-bold text-xl line-clamp-3">
            {{ store.pickedComic.title }}
            {{ store.pickedComic.subtitle ? `(${store.pickedComic.subtitle})` : '' }}
          </span>
          <span class="text-red">作者：{{ store.pickedComic.authors.join(', ') }}</span>
          <span class="text-gray">类型：{{ store.pickedComic.genres.join(' ') }}</span>
        </div>
      </div>
    </template>

    <n-dropdown
      placement="bottom-start"
      trigger="manual"
      :x="dropdownX"
      :y="dropdownY"
      :options="dropdownOptions"
      :show="dropdownShowing"
      @clickoutside="dropdownShowing = false" />
  </div>
</template>

<style scoped>
.selection-container {
  @apply select-none overflow-auto;
}

.selection-container .selected {
  @apply bg-[rgb(204,232,255)];
}

.selection-container .downloaded {
  @apply bg-[rgba(24,160,88,0.16)];
}

:deep(.n-checkbox__label) {
  @apply overflow-hidden whitespace-nowrap text-ellipsis;
}

:global(.selection-area) {
  @apply bg-[rgba(46,115,252,0.5)];
}
</style>
