// src/AppContent.vue
<script setup lang="tsx">
import { commands } from './bindings.ts'
import { Avatar, Button, Tabs, TabsProps } from 'antd'
import LoginDialog from './dialogs/LoginDialog.vue'
import ProgressesPane from './panes/ProgressesPane/ProgressesPane.tsx'
import { CurrentTabName } from './types.ts'
import SearchPane from './panes/SearchPane.tsx'
import ChapterPane from './panes/ChapterPane.tsx'
import FavoritePane from './panes/FavoritePane.tsx'
import DownloadedPane from './panes/DownloadedPane/DownloadedPane.tsx'
import LogDialog from './dialogs/LogDialog.vue'
import AboutDialog from './dialogs/AboutDialog.vue'
import SettingsDialog from './dialogs/SettingsDialog.vue'
import { onMounted, ref, watch } from 'vue'
import { useMessage, useNotification } from 'naive-ui'
import { useStore } from './store.ts'
import { PhClockCounterClockwise, PhGearSix, PhInfo, PhUser } from '@phosphor-icons/vue'

const store = useStore()

const notification = useNotification()
const message = useMessage()

const logDialogShowing = ref<boolean>(false)
const loginDialogShowing = ref<boolean>(false)
const settingsDialogShowing = ref<boolean>(false)
const aboutDialogShowing = ref<boolean>(false)

watch(
  () => store.config,
  async () => {
    if (store.config === undefined) {
      return
    }
    await commands.saveConfig(store.config)
    message.success('保存配置成功')
  },
  { deep: true },
)

watch(
  () => store.config?.cookie,
  async (value, oldValue) => {
    if (store.config === undefined) {
      return
    }
    if (oldValue !== undefined && oldValue !== '' && value === '') {
      // 如果旧的 cookie 不为空，新的 cookie 为空，相当于退出登录
      store.userProfile = undefined
      store.config.cookie = ''
      message.success('已退出登录')
      return
    } else if (value === undefined || value === '') {
      // 如果 cookie 为空，说明用户没有登录
      return
    }

    const result = await commands.getUserProfile()
    if (result.status === 'error') {
      console.error(result.error)
      store.userProfile = undefined
      return
    }
    store.userProfile = result.data
    message.success('获取用户信息成功')
  },
)

onMounted(async () => {
  // 屏蔽浏览器右键菜单
  document.oncontextmenu = (event) => {
    event.preventDefault()
  }
  // 获取配置
  store.config = await commands.getConfig()
  // 检查日志目录大小
  const result = await commands.getLogsDirSize()
  if (result.status === 'error') {
    console.error(result.error)
    return
  }
  if (result.data > 50 * 1024 * 1024) {
    notification.warning({
      title: '日志目录大小超过50MB，请及时清理日志文件',
      description: () => (
        <>
          <div>
            点击右上角的 <span class="bg-gray-2 px-1">查看日志</span> 按钮
          </div>
          <div>
            里边有 <span class="bg-gray-2 px-1">打开日志目录</span> 按钮
          </div>
          <div>
            你也可以在里边取消勾选 <span class="bg-gray-2 px-1">输出文件日志</span>
          </div>
          <div>这样将不再产生文件日志</div>
        </>
      ),
    })
  }
})
</script>

<template>
  <div v-if="store.config !== undefined" class="h-screen flex flex-col">
    <div class="flex gap-1 pt-2 px-2">
      <n-input-group>
        <n-input-group-label>Cookie</n-input-group-label>
        <n-input v-model:value="store.config.cookie" placeholder="手动输入或点击右侧的按钮登录" clearable />
        <n-button type="primary" @click="loginDialogShowing = true">
          <template #icon>
            <n-icon size="20">
              <PhUser />
            </n-icon>
          </template>
          登录
        </n-button>
      </n-input-group>

      <div v-if="store.userProfile !== undefined" class="flex items-center">
        <NAvatar :src="store.userProfile.avatar" round />
        <span class="whitespace-nowrap">{{ store.userProfile.username }}</span>
      </div>
    </div>

    <div class="flex flex-1 overflow-hidden">
      <n-tabs class="h-full w-1/2" v-model:value="store.currentTabName" type="line" size="small" animated>
        <!--        <n-tab-pane class="h-full overflow-auto p-0!" name="search" tab="漫画搜索" display-directive="show">-->
        <!--          <SearchPane />-->
        <!--        </n-tab-pane>-->
        <!--        <n-tab-pane class="h-full overflow-auto p-0!" name="favorite" tab="漫画收藏" display-directive="show">-->
        <!--          <FavoritePane />-->
        <!--        </n-tab-pane>-->
        <!--        <n-tab-pane class="h-full overflow-auto p-0!" name="downloaded" tab="本地库存" display-directive="show">-->
        <!--          <DownloadedPane />-->
        <!--        </n-tab-pane>-->
        <!--        <n-tab-pane class="h-full overflow-auto p-0!" name="chapter" tab="章节详情" display-directive="show">-->
        <!--          <ChapterPane />-->
        <!--        </n-tab-pane>-->
      </n-tabs>

      <div class="w-1/2 overflow-auto flex flex-col">
        <div
          class="flex min-h-8.5 gap-col-1 mx-2 items-center border-solid border-0 border-b box-border border-[rgb(239,239,245)]">
          <div class="text-xl font-bold box-border">下载列表</div>
          <div class="flex-1" />
          <n-button size="small" @click="logDialogShowing = true">
            <template #icon>
              <n-icon size="20">
                <PhClockCounterClockwise />
              </n-icon>
            </template>
            日志
          </n-button>
          <n-button size="small" @click="settingsDialogShowing = true">
            <template #icon>
              <n-icon size="20">
                <PhGearSix />
              </n-icon>
            </template>
            配置
          </n-button>
          <n-button size="small" @click="aboutDialogShowing = true">
            <template #icon>
              <n-icon size="20">
                <PhInfo />
              </n-icon>
            </template>
            关于
          </n-button>
        </div>
        <!--        <ProgressesPane />-->
      </div>

      <LoginDialog v-model:showing="loginDialogShowing" />
      <LogDialog v-model:showing="logDialogShowing" />
      <SettingsDialog v-model:showing="settingsDialogShowing" />
      <AboutDialog v-model:showing="aboutDialogShowing" />
    </div>
  </div>
</template>

// src/AppContent.tsx
import { useEffect, useState } from 'react'
import { Comic, commands, Config, UserProfile } from './bindings.ts'
import { App as AntdApp, Avatar, Button, Input, Tabs, TabsProps } from 'antd'
import LoginDialog from './components/LoginDialog.tsx'
import DownloadingPane from './panes/DownloadingPane.tsx'
import { CurrentTabName } from './types.ts'
import SearchPane from './panes/SearchPane.tsx'
import ChapterPane from './panes/ChapterPane.tsx'
import FavoritePane from './panes/FavoritePane.tsx'
import DownloadedPane from './panes/DownloadedPane.tsx'
import LogViewer from './components/LogViewer.tsx'

interface Props {
  config: Config
  setConfig: (value: Config | undefined | ((prev: Config | undefined) => Config | undefined)) => void
}

function AppContent({ config, setConfig }: Props) {
  const { message } = AntdApp.useApp()

  const [userProfile, setUserProfile] = useState<UserProfile>()
  const [loginDialogShowing, setLoginDialogShowing] = useState<boolean>(false)
  const [logViewerShowing, setLogViewerShowing] = useState<boolean>(false)
  const [pickedComic, setPickedComic] = useState<Comic>()

  useEffect(() => {
    if (config === undefined) {
      return
    }

    commands.saveConfig(config).then(async () => {
      message.success('保存配置成功')
    })
  }, [config, message])

  useEffect(() => {
    if (config.cookie === '') {
      return
    }

    commands.getUserProfile().then(async (result) => {
      if (result.status === 'error') {
        console.error(result.error)
        setUserProfile(undefined)
        return
      }

      setUserProfile(result.data)
      message.success('获取用户信息成功')
    })
  }, [config.cookie, message])

  async function test() {
    const result = await commands.getLogsDirSize()
    console.log(result)
  }

  const [currentTabName, setCurrentTabName] = useState<CurrentTabName>('search')

  const tabItems: TabsProps['items'] = [
    {
      key: 'search',
      label: '漫画搜索',
      children: <SearchPane setPickedComic={setPickedComic} setCurrentTabName={setCurrentTabName} />,
    },
    {
      key: 'favorite',
      label: '漫画收藏',
      children: (
        <FavoritePane userProfile={userProfile} setPickedComic={setPickedComic} setCurrentTabName={setCurrentTabName} />
      ),
    },
    {
      key: 'downloaded',
      label: '本地库存',
      children: (
        <DownloadedPane
          config={config}
          setConfig={setConfig}
          setPickedComic={setPickedComic}
          currentTabName={currentTabName}
          setCurrentTabName={setCurrentTabName}
        />
      ),
    },
    {
      key: 'chapter',
      label: '章节详情',
      children: <ChapterPane pickedComic={pickedComic} setPickedComic={setPickedComic} />,
    },
  ]

  return (
    <div className="h-screen flex flex-col">
      <div className="flex">
        <Input
          prefix="Cookie："
          value={config.cookie}
          onChange={(e) => setConfig({ ...config, cookie: e.target.value })}
          allowClear={true}
        />
        <Button type="primary" onClick={() => setLoginDialogShowing(true)}>
          账号登录
        </Button>
        <Button onClick={() => setLogViewerShowing(true)}>查看日志</Button>
        <Button onClick={test}>测试用</Button>
        {userProfile !== undefined && (
          <div className="flex items-center">
            <Avatar src={userProfile.avatar} />
            <span className="whitespace-nowrap">{userProfile.username}</span>
          </div>
        )}
      </div>
      <div className="flex flex-1 overflow-hidden">
        <Tabs
          size="small"
          items={tabItems}
          className="h-full basis-1/2"
          activeKey={currentTabName}
          onChange={(key) => setCurrentTabName(key as CurrentTabName)}
        />
        <DownloadingPane className="h-full basis-1/2 overflow-auto" config={config} setConfig={setConfig} />
      </div>

      <LoginDialog
        loginDialogShowing={loginDialogShowing}
        setLoginDialogShowing={setLoginDialogShowing}
        config={config}
        setConfig={setConfig}
      />
      <LogViewer
        logViewerShowing={logViewerShowing}
        setLogViewerShowing={setLogViewerShowing}
        config={config}
        setConfig={setConfig}
      />
    </div>
  )
}

export default AppContent
